export const GET_ALL_CHARACTERS = "GET_ALL_CHARACTERS";
export const GET_CHARACTER_DETAILS = "GET_CHARACTER_DETAILS";
export const CLEAN_CHARACTER_DETAILS = "CLEAN_CHARACTER_DETAILS";
export const CLEAN_CHARACTERS = "CLEAN_CHARACTERS";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const DELETE_FAVORITE = "DELETE_FAVORITE";
export const FILTER = "FILTER";
export const ORDER = "ORDER";
